version: '3'

services:
  django_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app


# version: '3'

# services:
#   web:
#     image: kumarsumit74604/djangoproject:latest
#     ports:
#       - "9000:9000"
