

name: Build Code




on:
  workflow_run:
    workflows: ["Specify Python Version"]
    types:
      - completed

jobs:
  specify_python_version:
    runs-on: ubuntu-latest
    outputs:
      python-version: ${{ steps.set_up_python.outputs.python-version }}
    steps:
      - name: Set up Python
        id: set_up_python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

  build:
    runs-on: ubuntu-latest
    needs: specify_python_version
    strategy:
      matrix:
        python-version: ${{fromJson(needs.specify_python_version.outputs.python-version)}}  # Use output from specify_python_version job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python3 -m venv ./env
          source env/bin/activate
          pip install --upgrade -r requirements.txt






