

name: Build Code



on:
  workflow_run:
    workflows: ["Specify Python Version"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    
    strategy:
      matrix:
        python-version: ${{fromJson(needs.specify_python_version.outputs.python-version)}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python3 -m venv ./env
          source env/bin/activate
          pip install --upgrade -r requirements.txt


  # Add a standalone job without any dependencies
  check_syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Check YAML syntax
        run: echo "Checking syntax"


