#
name: Build Code

on:
  push:
    branches: [master]


jobs:
  build:
    runs-on: ubuntu-latest
    needs: specify_version
    strategy:
      matrix:
        python-version: ${{fromJson(needs.specify_version.outputs.python-version)}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python3 -m venv ./env
          source env/bin/activate
          pip install --upgrade -r requirements.txt


