name: Build Code

on:
  workflow_run:
    workflows: ["Specify_Python_Version"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    needs: specify_python_version
    strategy:
      matrix:
        python-version: '${{fromJson(needs.specify_python_version.outputs.python-version)}}'  # Ensure the version is treated as a string
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python3 -m venv ./env
          source env/bin/activate
          pip install --upgrade -r requirements.txt
