name: Deploy Code




jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Depends on the 'build' job

    steps:
      - name: Check and kill port 8000 if running
        run: |
          if lsof -Pi :8000 -sTCP:LISTEN -t >/dev/null ; then
            echo "Port 8000 is already in use. Killing the process..."
            kill $(lsof -t -i:8000)
            echo "Process killed successfully."
          else
            echo "Port 8000 is not in use."
          fi
        shell: bash

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
          audience: sts.amazonaws.com

      - name: Deploy Django project
        run: |
          # Assuming the path to your Django project is correct
          cd /home/ubuntu/actions-runner/_work/NCS_folder/NCS_folder
          python manage.py runserver 0.0.0.0:8000 &




