name: Deploy Django to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Django
        run: |
          DRY_RUN=$1

          echo "Pulling latest code from repository..."
          # Skip actual git pull in dry run
          [ "$DRY_RUN" != "true" ] && git pull origin master
          
    
          
          echo "Installing dependencies..."
          # Skip actual installation in dry run
          [ "$DRY_RUN" != "true" ] && pip install django 

          # echo "Running migrations..."
          # # Skip actual migrations in dry run
          # [ "$DRY_RUN" != "true" ] && python manage.py migrate

          # echo "Restarting the server..."
          # # Skip actual restart in dry run
          # [ "$DRY_RUN" != "true" ] && sudo systemctl restart myapp

          echo "Deployment complete."

      - name: Run Deployment
        run: |
          ssh -i ${{ secrets.demo_project.pem }} ec2-user@18.141.209.54 'bash -s' < deploy_script.sh
        env:
          ACTIONS_RUNNER_DEBUG: false

      - name: Dry Run Deployment
        run: |
          ssh -i ${{ secrets.demo_project.pem }} ec2-user@18.141.209.54 'bash -s' < deploy_script.sh
        env:
          ACTIONS_RUNNER_DEBUG: true
