name: Specify Python Version

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version to use (e.g., 3.6, 3.7, 3.8)'
        required: true
        default: '3.x'

jobs:
  specify_version:
    runs-on: ubuntu-latest
    outputs:
      python-version: ${{ steps.set_up_python.outputs.python-version }}

    steps:
      - name: Set up Python ${{ github.event.inputs.python-version }}
        id: set_up_python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ github.event.inputs.python-version }}









          