name: Specify Python Version

on:
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version to use (e.g., 3.6, 3.7, 3.8)'
        required: true
        default: '3.x'

jobs:
  specify_version:
    runs-on: ubuntu-latest
    outputs:
      python-version: ${{ steps.set_up_python.outputs.python-version }}

    steps:
      - name: Set up Python ${{ github.event.inputs.python-version }}
        id: set_up_python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ github.event.inputs.python-version }}

          

name: Build Code
on:
    push:
        branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest
        needs: specify_version
        strategy:
            matrix:
                python-version: ${{fromJson(needs.specify_version.outputs.python-version)}}
                
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v3
              with:
                    python-version: ${{ matrix.python-version }}
            
            - name: Install Dependencies
              run: |
                python3 -m venv ./env
                source env/bin/activate
                pip install --upgrade -r requirements.txt
            